-- +goose Up
INSERT INTO routes (external_id, name, created_at, updated_at) VALUES
    ('1',    'Bronzeville/Union Station',            NOW(), NOW()),
    ('2',    'Hyde Park Express',                    NOW(), NOW()),
    ('3',    'King Drive',                           NOW(), NOW()),
    ('4',    'Cottage Grove',                        NOW(), NOW()),
    ('X4',   'Cottage Grove Express',                NOW(), NOW()),
    ('N5',   'South Shore Night Bus',                NOW(), NOW()),
    ('6',    'Jackson Park Express',                 NOW(), NOW()),
    ('7',    'Harrison',                             NOW(), NOW()),
    ('8',    'Halsted',                              NOW(), NOW()),
    ('8A',   'South Halsted',                        NOW(), NOW()),
    ('9',    'Ashland',                              NOW(), NOW()),
    ('X9',   'Ashland Express',                      NOW(), NOW()),
    ('11',   'Lincoln',                              NOW(), NOW()),
    ('12',   'Roosevelt',                            NOW(), NOW()),
    ('J14',  'Jeffery Jump',                         NOW(), NOW()),
    ('15',   'Jeffery Local',                        NOW(), NOW()),
    ('18',   '16th/18th',                            NOW(), NOW()),
    ('19',   'United Center Express',                NOW(), NOW()),
    ('20',   'Madison',                              NOW(), NOW()),
    ('21',   'Cermak',                               NOW(), NOW()),
    ('22',   'Clark',                                NOW(), NOW()),
    ('24',   'Wentworth',                            NOW(), NOW()),
    ('26',   'South Shore Express',                  NOW(), NOW()),
    ('28',   'Stony Island',                         NOW(), NOW()),
    ('29',   'State',                                NOW(), NOW()),
    ('30',   'South Chicago',                        NOW(), NOW()),
    ('31',   '31st',                                 NOW(), NOW()),
    ('34',   'South Michigan',                       NOW(), NOW()),
    ('35',   '31st/35th',                            NOW(), NOW()),
    ('36',   'Broadway',                             NOW(), NOW()),
    ('37',   'Sedgwick',                             NOW(), NOW()),
    ('39',   'Pershing',                             NOW(), NOW()),
    ('43',   '43rd',                                 NOW(), NOW()),
    ('44',   'Wallace-Racine',                       NOW(), NOW()),
    ('47',   '47th',                                 NOW(), NOW()),
    ('48',   'South Damen',                          NOW(), NOW()),
    ('49',   'Western',                              NOW(), NOW()),
    ('49B',  'North Western',                        NOW(), NOW()),
    ('X49',  'Western Express',                      NOW(), NOW()),
    ('50',   'Damen',                                NOW(), NOW()),
    ('51',   '51st',                                 NOW(), NOW()),
    ('52',   'Kedzie',                               NOW(), NOW()),
    ('52A',  'South Kedzie',                         NOW(), NOW()),
    ('53',   'Pulaski',                              NOW(), NOW()),
    ('53A',  'South Pulaski',                        NOW(), NOW()),
    ('54',   'Cicero',                               NOW(), NOW()),
    ('54A',  'North Cicero/Skokie Blvd.',            NOW(), NOW()),
    ('54B',  'South Cicero',                         NOW(), NOW()),
    ('55',   'Garfield',                             NOW(), NOW()),
    ('55A',  '55th/Austin',                          NOW(), NOW()),
    ('55N',  '55th/Narragansett',                    NOW(), NOW()),
    ('56',   'Milwaukee',                            NOW(), NOW()),
    ('57',   'Laramie',                              NOW(), NOW()),
    ('59',   '59th/61st',                            NOW(), NOW()),
    ('60',   'Blue Island/26th',                     NOW(), NOW()),
    ('62',   'Archer',                               NOW(), NOW()),
    ('62H',  'Archer/Harlem',                        NOW(), NOW()),
    ('63',   '63rd',                                 NOW(), NOW()),
    ('63W',  'West 63rd',                            NOW(), NOW()),
    ('65',   'Grand',                                NOW(), NOW()),
    ('66',   'Chicago',                              NOW(), NOW()),
    ('67',   '67th-69th-71st',                       NOW(), NOW()),
    ('68',   'Northwest Highway',                    NOW(), NOW()),
    ('70',   'Division',                             NOW(), NOW()),
    ('71',   '71st/South Shore',                     NOW(), NOW()),
    ('72',   'North',                                NOW(), NOW()),
    ('73',   'Armitage',                             NOW(), NOW()),
    ('74',   'Fullerton',                            NOW(), NOW()),
    ('75',   '74th-75th',                            NOW(), NOW()),
    ('76',   'Diversey',                             NOW(), NOW()),
    ('77',   'Belmont',                              NOW(), NOW()),
    ('78',   'Montrose',                             NOW(), NOW()),
    ('79',   '79th',                                 NOW(), NOW()),
    ('80',   'Irving Park',                          NOW(), NOW()),
    ('81',   'Lawrence',                             NOW(), NOW()),
    ('81W',  'West Lawrence',                        NOW(), NOW()),
    ('82',   'Kimball-Homan',                        NOW(), NOW()),
    ('84',   'Peterson',                             NOW(), NOW()),
    ('85',   'Central',                              NOW(), NOW()),
    ('85A',  'North Central',                        NOW(), NOW()),
    ('86',   'Narragansett/Ridgeland',               NOW(), NOW()),
    ('87',   '87th',                                 NOW(), NOW()),
    ('88',   'Higgins',                              NOW(), NOW()),
    ('90',   'Harlem',                               NOW(), NOW()),
    ('91',   'Austin',                               NOW(), NOW()),
    ('92',   'Foster',                               NOW(), NOW()),
    ('93',   'California/Dodge',                     NOW(), NOW()),
    ('94',   'California',                           NOW(), NOW()),
    ('95',   '95th',                                 NOW(), NOW()),
    ('96',   'Lunt',                                 NOW(), NOW()),
    ('97',   'Skokie',                               NOW(), NOW()),
    ('100',  'Jeffery Manor Express',                NOW(), NOW()),
    ('103',  'West 103rd',                           NOW(), NOW()),
    ('106',  'East 103rd',                           NOW(), NOW()),
    ('108',  'Halsted/95th',                         NOW(), NOW()),
    ('111',  '111th/King Drive',                     NOW(), NOW()),
    ('111A', 'Pullman Shuttle',                      NOW(), NOW()),
    ('112',  'Vincennes/111th',                      NOW(), NOW()),
    ('115',  'Pullman/115th',                        NOW(), NOW()),
    ('119',  'Michigan/119th',                       NOW(), NOW()),
    ('120',  'Ogilvie/Streeterville Express',        NOW(), NOW()),
    ('121',  'Union/Streeterville Express',          NOW(), NOW()),
    ('124',  'Navy Pier',                            NOW(), NOW()),
    ('125',  'Water Tower Express',                  NOW(), NOW()),
    ('126',  'Jackson',                              NOW(), NOW()),
    ('134',  'Stockton/LaSalle Express',             NOW(), NOW()),
    ('135',  'Clarendon/LaSalle Express',            NOW(), NOW()),
    ('136',  'Sheridan/LaSalle Express',             NOW(), NOW()),
    ('143',  'Stockton/Michigan Express',            NOW(), NOW()),
    ('146',  'Inner Lake Shore/Michigan Exp.',       NOW(), NOW()),
    ('147',  'Outer DuSable Lake Shore Exp.',        NOW(), NOW()),
    ('148',  'Clarendon/Michigan Express',           NOW(), NOW()),
    ('151',  'Sheridan',                             NOW(), NOW()),
    ('152',  'Addison',                              NOW(), NOW()),
    ('155',  'Devon',                                NOW(), NOW()),
    ('156',  'LaSalle',                              NOW(), NOW()),
    ('157',  'Streeterville/Taylor',                 NOW(), NOW()),
    ('165',  'West 65th',                            NOW(), NOW()),
    ('169',  '69th-UPS Express',                     NOW(), NOW()),
    ('171',  'U. of Chicago/Hyde Park',              NOW(), NOW()),
    ('172',  'U. of Chicago/Kenwood',                NOW(), NOW()),
    ('192',  'U. of Chicago Hospitals Express',      NOW(), NOW()),
    ('201',  'Central/Ridge',                        NOW(), NOW()),
    ('206',  'Evanston Circulator',                  NOW(), NOW())
ON CONFLICT (external_id) DO NOTHING;

-- +goose Down
DELETE FROM routes WHERE external_id IN (
    '1','2','3','4','X4','N5','6','7','8','8A','9','X9','11','12','J14','15',
    '18','19','20','21','22','24','26','28','29','30','31','34','35','36','37',
    '39','43','44','47','48','49','49B','X49','50','51','52','52A','53','53A',
    '54','54A','54B','55','55A','55N','56','57','59','60','62','62H','63','63W',
    '65','66','67','68','70','71','72','73','74','75','76','77','78','79','80',
    '81','81W','82','84','85','85A','86','87','88','90','91','92','93','94','95',
    '96','97','100','103','106','108','111','111A','112','115','119','120','121',
    '124','125','126','134','135','136','143','146','147','148','151','152','155',
    '156','157','165','169','171','172','192','201','206'
);
